title: Sam's Tech blog
description: > # this means to ignore newlines until "baseurl:"
  A blog filled with my previous projects, tutorials and other bits of tech
  goodness.
permalink: ':title/'
url: "SamHibbert.github.io"

# Author Settings
author: Sam Hibbert
author-img: me.png
about-author: I make games, game engines and other bits of software.
social-github: SamHibb
social-linkedin: samuel-hibbert-5603a81b3
social-email: samhibb16@gmail.com

# Disqus
discus-identifier: samhibb-github-io

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]